feat(server): add TeacherCreateInput, TeacherUpdateInput DTO's, imple…
hayrullahalper/edupayroll pull request #10
Opened 2024-06-13 21:44 UTC by hayrullahalper

…ment updateTeacher, createTeacher methods

2024-06-14 19:26 UTC, halisyucel requested changes

2024-06-14 19:26 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/controller/teacher/TeacherController.java
> +        var updatedTeacher = teacherService.update(teacher, input.name, input.branch, input.identityNo);
input'dan gelen pojo classlarda getter'ları kullanalım

2024-06-14 19:26 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/controller/teacher/TeacherController.java
> +        return ResponseEntity.ok().body(Response.data(TeacherMapper.toDTO(updatedTeacher)).build());
elzem değil detay:

okunaklılığı arttırmak adına bu tarz chain metotlarda alt alta yazsak güzel olur.

```java
return ResponseEntity
                .ok()
                .body(Response
                        .data(UserMapper.toDTO(user))
                        .build()
                );
```

2024-06-14 19:26 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/controller/teacher/TeacherExceptionHandler.java
> +                .status(HttpStatus.UNAUTHORIZED)
bunu not found yapalım. kişinin erişimi olmadığı kaynakları engellemeyi access denied hatası ile globalde tutuyoruz zaten. access denied hatasının kullanımı service içinde göstereceğim. not found'u kişinin aradığı teacher gerçekten yoksa atmış olacağız.

ayrıca bu tarz controller exception handler'larında hatanın mesajları exception classından gelsin. ex.getMessage() gibi. o mesajda hatanın atıldığı yerde belirlesin. ama genellikle bunu exceptionun static generator metodunda yapıyoruz. `byUser` gibi

2024-06-14 19:26 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/service/teacher/TeacherService.java
> +
elzem olmayan iki detay.

```java
create(
            String name,
            String email,
            String passwordHash
    )
```
    
böyle parametrenin çok olduğu yerlerde aşağı kırmak iyi oluyor.
aynı şekil bu tarz kırmalarda iyi oluyor.
    
```java
       if (schoolName != null)
            school.setName(schoolName);

        if (editorName != null)
            school.setEditorName(editorName);

        if (editorTitle != null)
            school.setEditorTitle(editorTitle);

        if (principalName != null)
            school.setPrincipalName(principalName);
            
```

2024-06-14 19:26 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/service/teacher/TeacherService.java
> +        TeacherEntity teacher = new TeacherEntity();
`var` kullanmak kalabalığı azaltıyor. zaten herhangi bir cast işlemi yapmıyoruz.

2024-06-14 19:26 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/service/teacher/TeacherService.java
> +        return teacherRepository.getReferenceById(uuid);
burada öncelikle `findById` metodunu kullanmalıyız.
mevcut teacher'i çektikten sonra null check yapmalıyız. eğer yoksa user not found fırlatmalıyız. 
varsa teacher bu kullanıcıya mı ait kontrolü yapmalıyız. eğer değilse access denied exception fırlatmalıyız. `utils/exception` altında bulunuyor.

ardından teacher'ı dönmeliyiz.

2024-06-14 19:26 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/controller/teacher/TeacherController.java
> +        var teacher = teacherService.getById(user, UUID.fromString(input.id));
input pojo'sunda id'yi UUID yaparsan burada boşuna çevirmek zorunda kalmazsın.

2024-06-17 18:17 UTC, hayrullahalper commented on packages/api/src/main/java/com/incubator/edupayroll/service/teacher/TeacherService.java
> +
hocam create methodu zaten kısa onu gerekli bulmadım, if statementlarını düzelttim

2024-06-17 18:17 UTC, hayrullahalper commented on packages/api/src/main/java/com/incubator/edupayroll/service/teacher/TeacherService.java
> +        TeacherEntity teacher = new TeacherEntity();
iyi dedin hocam hallettim

2024-06-17 21:07 UTC, halisyucel requested changes

2024-06-17 21:07 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/service/teacher/TeacherService.java
> +        var teacherEntity = maybeTeacher.get();
burası için şöyle bir metot var. kullanımı kolaylaştırıyor.

```java
var maybeTeacher = teacherRepository.findById(uuid);
var teacher = maybeUser.orElseThrow(() -> TeacherNotFoundException.byUser(user));
```

2024-06-17 21:07 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/service/teacher/TeacherService.java
> +//            throw AccessDeniedException.byUser(user);
burayı neden yoruma aldın anlayamadım

2024-06-17 21:07 UTC, halisyucel commented on packages/api/src/main/java/com/incubator/edupayroll/service/teacher/TeacherService.java
> +            teacher.setName(name);
teacher create ederken null check yapmamıza gerek yok. bu değerler zaten null gelmeyecek ve db'ye de null gidemez hata verir

2024-06-26 16:02 UTC, merged